export const TaskTypes = {
    GET_TASKS: 'GET_TASKS',
    ADD_TASK: 'ADD_TASK',
    SET_TASK: 'SET_TASK',
    REMOVE_TASK: 'REMOVE_TASK',
    TOGGLE_TASK: 'TOGGLE_TASK',
    SET_TASK_PRIORITY: 'SET_TASK_PRIORITY',
    SET_TASK_DUE_DATE: 'SET_TASK_DUE_DATE'
}